### ISSUE TITLE
Name not captured in public user profile - google 

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#105]
#71 assumed the user's name would be captured by the auth provider, but that might not be the case.

### Steps to reproduce

- Select to register as public
- Sign in with Google
- Profile page contains email but not name (user must enter phone to proceed with registration)

### Expected
- Name on profile page auto-filled with user's name from their Google account
- If not achievable, then make Name a required field to be entered by user to complete the profile

![Screenshot_20210909-141117](https://user-images.githubusercontent.com/15659642/132767340-e08c5e92-6b12-46c3-9cc7-5c5635a02633.png)

**Comment by stdavis** [comment]
I believe that this is only an issue for Android in stand-alone builds (not dev). The fix is likely in `google-standalone.js`.

**Comment by nathankota** [comment]
Fixed beyond version .365. I un/re-installed to version .372 and it looks good.
