### ISSUE TITLE
UtahID login error

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#106]
From TJ Cook:

- Apple device
- Test flight installed and signed into test flight using apple ID
- Tap contractor OR state agency
- Tap Sign in with UtahID

Result:

![image](https://user-images.githubusercontent.com/15659642/132768704-d121df22-73e7-465e-94bf-a9c8cec18bff.png)

**Comment by stdavis** [comment]
So it does not happen when he attempts to sign in via UtahID as public?

**Comment by stdavis** [comment]
This was solved by clicking on the "notify testers" link in TestFlight which allows TJ to download the latest version. He was running an older version that was broken. I'll add a note to my release steps to make sure that this doesn't happen again.

**Comment by nathankota** [comment]
worked for Rhett, waiting for confirmation from TJ

**Comment by nathankota** [comment]
confirmed...all is well again
