### ISSUE TITLE
Live animal phone number 

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#107]
What phone number should be included on the app in the case that a live animal is encountered? 

![Report_injured_animal](https://user-images.githubusercontent.com/15659642/133099748-7c27aae4-71a7-4cca-a332-d83dfd18915b.png)

**Comment by nathankota** [comment]
[PSAPs](https://opendata.gis.utah.gov/datasets/utah-public-safety-answering-point-boundaries/explore) are the best option. What are the options for finding the proper contact either by making the user choose the right one (easiest?), or gathering their device location and providing the proper PSAP number (hardest?)

**Comment by stdavis** [comment]
I think that it wouldn't be too difficult to query that feature service in AGOL and return the appropriate number. We just need a fallback for when the user is offline.

**Comment by stdavis** [comment]
@nathankota Do we have a fallback number for offline for this? I can work on querying the PSAPs.

**Comment by nathankota** [comment]
Messaged Daniel for some guidance on this today.

**Comment by nathankota** [comment]
The offline message should be:

_If you encounter a live animal please contact your local law enforcement._

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/153941021-8e13aad5-25e0-4e8a-b3ed-8cd110bec31a.png)

![image](https://user-images.githubusercontent.com/1326248/153941108-e319212f-45c2-4b91-8450-3e678dc3640e.png)

**Comment by nathankota** [comment]
This works so I will close the issue, but I noticed one thing that I will put into a new issue.
