### ISSUE TITLE
Refreshing UtahID login fails on Android only

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#111]
# Reproduction - Android only
1. log into the application via UtahID
2. wait for your refresh token to expire (1 day)
3. attempt to submit a report

Error (while attempting to prompt for a new login):
![image](https://user-images.githubusercontent.com/1326248/138171052-6a2763a0-2cfe-4f8e-8418-7a36df480d50.png)

This error is being thrown from [within the `expo-auth-session` package](https://github.com/expo/expo/blob/1feda34603e393e3f0397720fd401d589d920d42/packages/expo-auth-session/src/AuthRequestHooks.ts#L89) with the cause being that the `request` object is undefined. I can't figure out why it's undefined at this point since I have logged its value within my own hook and it shows as a valid object.

Refreshing the access token with a valid refresh token is working fine. The problem only happens when the refresh token has expired.

I can debug this issue again after 2:06 PM on 10/21.

**Comment by stdavis** [comment]
This happened in staging for me this morning. :(

@steve I'd like to redeem a solve my problem coupon (do I have any left) for this one when you have some time.

**Comment by nathankota** [comment]
I got the same error (with a 401 on top of it). The app was not open on my device for 24 hours, but I did not logout during that time period and received the error when trying to submit a pick-up, followed by a public report.

**Comment by stdavis** [comment]
Thanks. Now, I am curious if it happens again after you update via the app store. And no, you don't have to have the app open for the entire 24 hours. Just don't log out during that time.

**Comment by nathankota** [comment]
Just updated the app and will try again after 24 hours

**Comment by nathankota** [comment]
Still an issue for me after updating to latest version.
