### ISSUE TITLE
2FA via the Utah Authenticator App does not work

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#112]
Daniel recorded a [helpful video](https://drive.google.com/file/d/1n6tgw7eMcHKKZ7rI2r-N3Oyhjd3e4KsU/view?usp=sharing) on how to reproduce this bug.

I'm guessing that the app re-mounts/re-authorizes when the user switches back to it after granting access from the authenticator app.

This works fine on iOS, it's only an issue on Android.

**Comment by nathankota** [comment]
validated
