### ISSUE TITLE
Account Deletion

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#115]
Maybe just instruct them to email an admin and request removal.

This is a [requirement for Facebook](https://developers.facebook.com/docs/development/create-an-app/app-dashboard/data-deletion-callback) and will need to be filled out in the Facebook app config.

**Comment by stdavis** [comment]
[Google wants to see this as well](https://support.google.com/googleplay/android-developer/answer/10787469?hl=en#:~:text=Whether%20or%20not%20you%20provide%20a%20way%20for%20users%20to%20request%20that%20their%20data%20is%20deleted.)

**Comment by stdavis** [comment]
I need an answer to the question of how much data is considered personal data that will be automatically deleted when a user deletes their account. All routes, pickups and reports submitted by them? I assume that this is the case but I wondered if DWR would be uncomfortable with this. Especially in the case of a contractor that ends their service with the state and just wants to delete their account. I'm guessing that we don't want to lose all of their data. Maybe we can legally get away with just deleting the user's PID information from the user table but keep everything else.

**Comment by nathankota** [comment]
@stdavis The preference would be to keep the submitted data, but delete the PID. I will try to find who to ask the question about what constitutes PID. 

> Maybe we can legally get away with just deleting the user's PID information from the user table but keep everything else.

**Comment by steveoh** [comment]
If you show me the data I can tell you with a decent amount of confidence what would be considered PII

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/155213991-24999638-d357-47f9-8775-122bcdd3ff05.png)
Everything else is linked to the `user_id` field but contains no other user data.

**Comment by steveoh** [comment]
email, first and last name, phone, and possibly organization are PII

**Comment by stdavis** [comment]
I'm going to move forward with this issue with the following proposal until we hear otherwise from the privacy folks:

When a user requests that their account be deleted, the following changes are made to their record within the `users` table:

| Column | New Value |
| --- | --- |
| `organization_id` | `null` |
| `role` | `<unchanged>` |
| `approved` | `<unchanged>` |
| `auth_provider` | `<unchanged>` |
| `auth_id` | "deleted" |
| `email` | "deleted" |
| `first_name` | "deleted" |
| `last_name` | "deleted" |
| `registered_date` | `<unchanged>` |
| `last_logged_in` | `<unchanged>` |
| `phone` | "deleted" |
|  `approved_date` | `<unchanged>` |

Everything else in the database would be untouched. @nathankota Are you good with this plan?

**Comment by nathankota** [comment]
Yes, that sounds good. Question: Why does `organization_id` become `null`, rather than "deleted"?

**Comment by nathankota** [comment]
@stdavis should we remove the `question` and `waiting` labels since we have a path forward, despite no client feedback yet?

**Comment by nathankota** [comment]
This worked for Utah ID. I signed in, deleted my account, tried to sign in with my deleted UtahID account and it prompted me to sign up again. I will also ask clients to test this with other account types (google and facebook).
