### ISSUE TITLE
Crosshair not appearing

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#117]
- Sign-in as state employee
- Click "plus" button to add an observation
- Select pick-up carcass
- Crosshair appeared
- Exit window
- Click Report a Carcass
- Crosshair does not appear
- Keep toggling between the report and pick-up and crosshair is more consistently absent

**Note:** It worked fine and consistently when logged-in as public and reporting a carcass

**Comment by stdavis** [comment]
I believe that this has been fixed in 353b834dcd25760516958c9148fee3f4d74f6bda

**Comment by nathankota** [comment]
validated
