### ISSUE TITLE
Environment is missing from new user registration email

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#119]
![image](https://user-images.githubusercontent.com/1326248/140089196-9e8ba0df-63f2-4e05-ab2f-4a2fa637b9d4.png)

**Comment by nathankota** [comment]
@stdavis Sorry to make you jog my memory again. Do I need to have someone new added as a tester first, then sign up to test this, or can I send an Android user the google test app link and have them install and sign up straight away?

**Comment by stdavis** [comment]
I believe that I have to add them manually to the list on the back end and then they can join the test via the [google play store test URL](https://play.google.com/apps/internaltest/4699387731848346247)

**Comment by nathankota** [comment]
K, I will need to find a lab rat tomorrow.

**Comment by nathankota** [comment]
Please add Rick, Jake and Zach as testers, and I will have one or more of them install the app and register to test this.

jdadams@utah.gov, rkelson@utah.gov, zbeck@utah.gov

**Comment by stdavis** [comment]
> Please add Rick, Jake and Zach as testers

For which platform? iOS or Android?

**Comment by nathankota** [comment]
Sorry I forgot that part! Jake and Zach are iOS. Not sure about Rick yet

**Comment by stdavis** [comment]
I've got them all added.

**Comment by nathankota** [comment]
![image](https://user-images.githubusercontent.com/15659642/159500459-2b91866e-0146-4f91-a2f9-f6e2bce21f38.png)
