### ISSUE TITLE
Eliminate text on role selection page

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#120]
Change first selection to simply

> Member of the public

![image](https://user-images.githubusercontent.com/15659642/141489652-b2bc6d45-7d58-49a7-8dac-b126ba589229.png)

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/142507912-b4173542-c0c7-4461-adb2-51eddb63061c.png)

**Comment by nathankota** [comment]
validated
