### ISSUE TITLE
Remove Welcome page

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#121]
The Welcome page is no longer needed. For contractor and agency users, skip this page and go straight to UtahID login. For public users, do something simple directly on the role selection page to show the possible logins (google, fb, utahid), such as a dialog or expand beneath the public selection.

![image](https://user-images.githubusercontent.com/15659642/141490905-cf0af695-d55e-44c9-b66e-093e93fb27ca.png)

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/142515055-31a4c16d-032f-4886-bc34-6344aae4c617.png)

**Comment by nathankota** [comment]
validated
