### ISSUE TITLE
Make Report button more apparent

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#123]
Make report button more visible and apparent. Wider and centered at the bottom, with some text.

![image](https://user-images.githubusercontent.com/15659642/141497210-06d7fcb7-8825-47a8-a283-12e4fcbd6413.png)

**Comment by nathankota** [comment]
Hold the press! Daniel said he will send a mockup of his preferred design.

**Comment by stdavis** [comment]
I think that the mockups from #31 show this button enough to build it.

**Comment by nathankota** [comment]
Looks great. Might add deer icon at some point, but that can be a different enhancement issue later.
