### ISSUE TITLE
Change location button icon

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#124]
Change my location button icon to something other than crosshairs, since that is what is used for setting location during reporting. Another icon possibility is an arrow:

![image](https://user-images.githubusercontent.com/15659642/141497877-9ecfcb56-fe98-44b8-b16f-33c2afde42d5.png)

**Comment by stdavis** [comment]
The top image (blue) is when location tracking is enabled and the bottom (white) is the opposite.

![image](https://user-images.githubusercontent.com/1326248/142516130-cdeff775-50e9-49a3-971d-2476e3ab2e74.png)

**Comment by nathankota** [comment]
validated
