### ISSUE TITLE
Change agency reporting options text

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#134]
**From:** _PICK UP A CARCASS_
**To:** _REPORT AND PICK UP A CARCASS_

![image](https://user-images.githubusercontent.com/15659642/141795112-3b469880-2cd8-4277-b159-8121071c0230.png)

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/142515145-0d05a87d-6dbc-4604-938c-d98e8933e7d6.png)

**Comment by nathankota** [comment]
validated
