### ISSUE TITLE
Species search by changes

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#137]
- change `frequent` to `frequently reported`, text wrapped so the two words appear on separate lines
- change `common` to `common name`, the two words also on separate lines

![image](https://user-images.githubusercontent.com/15659642/142418557-b6863b53-d3ae-4ebe-8180-10245191b4be.png)

**Comment by stdavis** [comment]
I had to shrink the text on smaller devices to prevent the longer words from being broken up.

![image](https://user-images.githubusercontent.com/1326248/144143840-51dfc44a-8083-402a-8591-91af4d0ab961.png)

![image](https://user-images.githubusercontent.com/1326248/144143906-ac8e9893-396c-42d7-96b6-c3fd30a8533a.png)

![image](https://user-images.githubusercontent.com/1326248/144143939-030d3263-cf9c-4a09-aeb2-724c6ca10470.png)
