### ISSUE TITLE
Let DWR know the preferred species image dimensions + shape

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#141]
Once the dimensions and shape of the species thumbnail images are determined for the species selection component, we can let DWR know so they can start compiling the images.

**Comment by stdavis** [comment]
Assuming the client is happy with the initial photos layout, the image size should be 150x150 pixels. I'm just leaving this comment here so that I don't forget.

**Comment by nathankota** [comment]
Client is good with 150 x 150

![image](https://user-images.githubusercontent.com/15659642/144311069-e6817c83-2f11-4d99-9889-a5e79a438a22.png)
