### ISSUE TITLE
Species component - no more buttons

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#142]
Show all species selections as a list, rather than as buttons, like the common name list appears now.  

![image](https://user-images.githubusercontent.com/15659642/142501363-5ff7ff05-a3d3-4d64-b78b-112fa1aab51e.png)

**Comment by stdavis** [comment]
https://user-images.githubusercontent.com/1326248/144141570-e71d5c29-b04b-4c57-bca2-f3bd41398d03.mp4


https://user-images.githubusercontent.com/1326248/144141589-ff8a2b70-8b51-4ed0-84fb-b100300006c1.mp4
