### ISSUE TITLE
Store all species fields in database

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#144]
Include in database all the attributes from [the species list](https://docs.google.com/spreadsheets/d/1jb0IREE3pPaK8sJqCKUf5IFUsw9-D_izX1grEsJ6iuo/edit#gid=0). 

If a user cannot fully ID the species, but makes one or two selections, then all subsequent data field entries should be "unknown". For example, if `Feathers` chosen, followed by `Unknown`, then the Class field in the table will contain "Birds", but the remaining fields will be "unknown". 

![image](https://user-images.githubusercontent.com/15659642/142503640-4fe132b7-e36d-411f-bcc3-5e6a05148132.png)

**Comment by stdavis** [comment]
I'm working under the assumption that we can leave the rare species value out of the report table. That doesn't seem like it would add any value. Let me know if this is incorrect.

**Comment by nathankota** [comment]
By report table you mean My Report, correct? If yes, I spoke with Daniel and we're thinking to just include the species common name (or "unknown") in the report table, because the values for some of the other species data fields might not match what they select. For example, "Feathers" would show up as "Birds" in the table.

**Comment by stdavis** [comment]
No, I'm talking about the report table in the database. I didn't see any value in storing the boolean rare species value in the report table. Do they care if the report was for a rare species after the fact? What if the rare species changed? I'll still store the values in the species table. I'll send you some specifics when I start working on this issue.

**Comment by stdavis** [comment]
Here's what the database design looks like after I've applied what my understanding is of the changes involved in this issue:
![image](https://user-images.githubusercontent.com/1326248/142866380-ddba4bd3-1e6e-4950-9ae3-4b58f881d7ea.png)

Notice the new `species` table and the new fields in the `report_infos` table (`species_id`, `common_name`, `scientific name`, `species_type`, `species_class`, `species_order`, `family`). My question is: do I need to add the `rare` field to the `report_infos` table? I'm assuming that it is not needed.

**Comment by nathankota** [comment]
> My question is: do I need to add the rare field to the report_infos table? I'm assuming that it is not needed.

I also do not think it is needed in the `report_infos` table since it is only used to produce a message (#148), but I have asked Daniel to make sure.

**Comment by nathankota** [comment]
> My question is: do I need to add the rare field to the report_infos table? I'm assuming that it is not needed.

Confirmed. The `rare` field does **not** need to be added to the `report_infos` table.
