### ISSUE TITLE
Species component - Rare species notification/message

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#148]
If a user selects a species where `Rare Species Warning` == `Yes` on the [species list](https://docs.google.com/spreadsheets/d/1jb0IREE3pPaK8sJqCKUf5IFUsw9-D_izX1grEsJ6iuo/edit#gid=0), then have a notification pop-up saying something about it being rare. Will get the text and other UI details from DWR.

**Comment by nathankota** [comment]
The message is below, and there just needs to be an option to close it after it appears so the user can consider it and decide if they want to change their species selection. 

_The species you selected is rare in this area. Please consider this selection carefully before submitting your report, or select a different species._

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/144144432-c14e6319-4cb5-4a72-9214-a1f92914d194.png)

![image](https://user-images.githubusercontent.com/1326248/144144696-a7f03d90-7a5b-4b4a-ad0b-50f0ec0c297b.png)

**Comment by nathankota** [comment]
looks good!
