### ISSUE TITLE
Add Routes to My Reports

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#154]

**Comment by nathankota** [comment]
This is the [Miro mockup](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3458764517497885988&cot=14). There is a question about including some of the possible date/time data in the report layout. I believe this also changes some of the [previous thought/mockup about Agency users' My Reports](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3458764517470341457&cot=14).

**Comment by stdavis** [comment]
> There is a question about including some of the possible date/time data in the report layout.

Can you clarify? Or should I just build this according to the latest mockups and move forward from there?

**Comment by nathankota** [comment]
I just wasn't sure if all of those _could_ be included. Yes, please move forward according to the latest mockups, and let me know if you come across any issues.

**Comment by nathankota** [comment]
looks great!
