### ISSUE TITLE
Standardize Design

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#155]
There have been a lot of iterations during development so some of the stuff that was built in the early days does not line up with newer stuff. Here's a list of things to check:

- [x] cancel buttons (don't forget registration page)
- [x] are you sure, alerts should have standardized text and button names
- [x] submit button style
	- [x] "Register" button on sign up profile page should be changed from yellow to blue
	- [x] "Update" button on profile page should be changed to blue
- [x] Profile, My Reports right icon should be lighter so that it doesn't appear tappable
- [x] "frequently reported" tab on species control should be shortened to "often reported" to prevent wrapping on smaller devices
![image](https://user-images.githubusercontent.com/1326248/192381730-1428bd5c-fc27-49b7-8a81-f6d8590c30de.png)
- [x] "Unknown" pill in confidence, age, and sex options should be changed from blue to less prominent color such as grey
- [x] "Submit Route" alert should have the buttons switched so that "Cancel" is on the left to match the other alert cancel buttons
- [x] "Canceled routes are delayed.." alert should have the "Cancel Route" button moved to the left side to match other alerts
- [x] Look at the [DTS design](https://utahdts.github.io/utah-design-system/#business) system and see if it has anything to add
- [x] set status bar (time, battery, etc) to white on map page

https://stdavis.notion.site/Roadkill-Design-Consistency-Study-27eb1a497ad84f178ad914b013aa0cc5

**Comment by nathankota** [comment]
let me know when you want to start checking these things and I will help

**Comment by stdavis** [comment]
Let's work through this after the next release.

**Comment by nathankota** [comment]
> Let's work through this after the next release.

Let me know how/when I can help.

**Comment by stdavis** [comment]
@nathankota I've collected a [bunch of screenshots](https://stdavis.notion.site/Roadkill-Design-Consistency-Study-27eb1a497ad84f178ad914b013aa0cc5) to help compare the design. After reviewing this, I added a handful of simple tweaks to the description of this issue. Please feel free to add/change/remove however you see fit. Let me know when it's ready for me to implement.

**Comment by nathankota** [comment]
The screenshots and recommended tweaks look and sound great. Well done picking up on all the little details. Please feel free to move forward. 



> * [x]  Profile, My Reports right icon should be lighter so that it doesn't appear tappable

This is the only one I'm not quite understanding. Not a big deal, just want to make sure I'm following along properly.

**Comment by stdavis** [comment]
> This is the only one I'm not quite understanding.

This was done a while ago. There used to be an icon on the upper-right side of the screen that was mistaken by some users as a tappable button. I ended up removing them altogether.

**Comment by stdavis** [comment]
I put the results of these changes at the bottom of [the notion page](https://www.notion.so/stdavis/Roadkill-Design-Consistency-Study-27eb1a497ad84f178ad914b013aa0cc5).

**Comment by nathankota** [comment]
I'm not going to nitpick each of these changes, but have been following them and believe this is completed and the client does not need to look at each one in great detail. If issues are recognized, we will deal with them.
