### ISSUE TITLE
Spinner layout issue

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#156]
On Android only:
![image](https://user-images.githubusercontent.com/1326248/150848058-be35fb8a-87a7-4ebf-ba79-417f9c7044c7.png)

Maybe something to do with elevation stuff?

**Comment by nathankota** [comment]
I never experienced this issue, but after logging out and back in several times, it seems to find my location just fine and get past the spinner (on Pixel 4 Android device).
