### ISSUE TITLE
Add background location disclosure statement

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#157]
In order to satisfy [Google Play requirements](https://support.google.com/googleplay/android-developer/answer/9799150#:~:text=%E2%80%9C%5BThis%20app%5D%20collects%20location%20data%20to%20enable%20%5B%22feature%22%5D%2C%20%5B%22feature%22%5D%2C%20%26%20%5B%22feature%22%5D%20even%20when%20the%20app%20is%20closed%20or%20not%20in%20use.%E2%80%9D). I wonder if we could just show it once when the user clicks on the track button for the first time.

**Comment by nathankota** [comment]
I like your idea of showing it once. Unlike some of the examples in the video, the app will only collect location data in the background while the app is in use. Let me know if we need to engage the client for preferred text in the disclosure, or for any legal representative engagement that might be needed.

**Comment by stdavis** [comment]
I wonder if we should have a legal expert review the entire app to make sure that we are on the up and up.

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/154116454-a6315683-0065-4299-86ef-bb96c3850d76.png)

**Comment by nathankota** [comment]
Validated. Great solution.
