### ISSUE TITLE
Let iOS users know that offline reports will expire in 7 days if not submitted

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#17]
Safari [just implemented](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/) a "security measure" that deletes all script-writable storage form (including local storage) "after seven days of Safari use without user interaction on the site". When a user attempts to submit a report without an internet connection, this app stores the reports in local storage. This expiration is specific to Safari and not part of the local storage spec. It also appears that Apple did this without much, if any advanced notice. There has been [some backlash](https://ar.al/2020/03/25/apple-just-killed-offline-web-apps-while-purporting-to-protect-your-privacy-why-thats-a-bad-thing-and-why-you-should-care/) but I'm not sure that it will make any difference.

In the near term, we should add a warning for Safari users that offline reports must be submitted within 7 days or they will be lost.

I'm not sure if there is a solution to this in the long term. It appears that Apple is not interested in preserving any sort of offline storage. @nathankota This may be a good reason to push on the next version of this app sooner rather than later. There is definitely a way around it by requiring users to submit within seven days, but it's a little concerning that we could lose reports.

**Comment by nathankota** [comment]
Are you thinking a pop-up type warning at a relevant step in the data collection workflow, or adding additional verbiage to the mobile page https://mapserv.utah.gov/wvc/mobile/? 

I will let DWR/UDOT know of this change, and inquire about their progress on an alternative app. Thank you for keeping up with changes such as these that affect the apps supported by AGRC.

**Comment by stdavis** [comment]
I was thinking some sort of popup that shows up when a report is stored locally.

**Comment by nathankota** [comment]
I like it, and will recommend to DWR/UDOT.

**Comment by stdavis** [comment]
Here's what the alert looks like:
![image](https://user-images.githubusercontent.com/1326248/78072880-1504a480-735d-11ea-912e-6dc6fec98a76.png)
It will only show up for iOS devices and desktop Safari.
