### ISSUE TITLE
Send approval/reject notification to user

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#173]
When a user is approved or rejected, send an email to them letting them know what action was taken.

Approval:
>Congratulations, you have been approved as `<role>` in the Wildlife-Vehicle Collision Reporter app.

Rejection:
>Unfortunately, your registration for the Wildlife-Vehicle Collision Reporter app has been declined. You may send an email to `<admin-email>` if you believe that this was a mistake.

@nathankota Does this verbiage look OK to you?

**Comment by nathankota** [comment]
@stdavis is there a hotmail account for me in the testing database? If not, I have one more email account I can use to test this feature.

**Comment by stdavis** [comment]
I don't see any @hotmail accounts in the user table in staging...

**Comment by nathankota** [comment]
The notification emails are working as expected. There may be another issue with post- approval and rejection functionality, but that will be a new issue.

### Approval Test:
Received the following admin emails:
![image](https://user-images.githubusercontent.com/15659642/163021669-2bc27805-4171-4ad0-9750-7262be38c021.png)

And the following user email:
![image](https://user-images.githubusercontent.com/15659642/163021819-9a7a21a9-47ae-44d1-8160-1d8458bf8f11.png)


### Rejection Test:
Admin email:
![image](https://user-images.githubusercontent.com/15659642/163022908-b027d4b4-5a49-4332-864a-d107d391d18a.png)

User email:
![image](https://user-images.githubusercontent.com/15659642/163023204-476cb18e-9053-41e0-9beb-a260e050ab62.png)
