### ISSUE TITLE
Let new contractor/agency users know that an approval is needed

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#174]
Let new contractor and agency users know that their account will be submitted for approval to admins but that they can still collect and submit data. This could be in the form of an alert displayed after they hit submit on the new user registration screen.

Maybe something like this:
>Thank you for registering! Your registration has been sent to system administrators for approval. You will get an email once your account has been approved. Please note that you may still collect and submit data before your account is approved.

@nathankota Are you good with this or do you have any improvements?

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/162488889-e6a4884a-a23b-4bc4-a36d-84f17faec71d.png)

**Comment by nathankota** [comment]
👍 
> Thank you for registering! Your registration has been sent to system administrators for approval. You will get an email once your account has been approved. Please note that you may still collect and submit data before your account is approved.

**Comment by nathankota** [comment]
@stdavis I deleted the account associated with kotanl@hotmail.com, then re-registered with it as an agency user, but did not receive the needs-approval notification.

**Comment by stdavis** [comment]
I wonder if your phone was caching your role. I never considered the use case of logging into the app with the same user but different roles. When you have a minute, we can go through this again together and verify using the database.

**Comment by nathankota** [comment]
Something was up with my account, but I have seen the notification when signing up previously, and it was working for Scott, so we can close this issue and see if the client testers come across any issues.
