### ISSUE TITLE
Use Client notification areas and contacts

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#177]
- ~[UDOT Maintenance Stations](https://maps.udot.utah.gov/central/rest/services/Maintenance/Station_Boundary_Buffer_for_Carcass_App/MapServer)~
- ~UDOT Contractors~
- UDWR Regions

**Comment by stdavis** [comment]
We do not have regions in the database currently. I have vague memories of helping Jessie get set up with a database connection so that she could input the notification areas but I could be wrong on that. Either way, I'm happy to add the data to the database if they want to send it to me. I believe that we have DWR regions somewhere but I'm guessing that we don't have email addresses associated with them.

**Comment by nathankota** [comment]
@jshapiro49 do you have the region contacts list available? We can help get it (and the spatial data) into the database if necessary.

**Comment by jshapiro49** [comment]
Yes, Scott did set me up with access to the database. However, I don't have access to the users_have_notification_areas or the species tables. Is this something you can grant me editing access to? Also, each region has two contacts; should I append the region boundaries twice? Looks like the notification area table can only have one contact per polygon. Here's a zipped shapefile of our notification regions with contact info for reference. 

[DWR_Notification_Regions.zip](https://github.com/agrc/roadkill-mobile/files/9397418/DWR_Notification_Regions.zip)

More of an FYI, ArcGIS Pro doesn't allow you to make edits to a CloudSQL database, but I can make these edits in QGIS.

**Comment by stdavis** [comment]
Just to give an update: I helped Jessie get access to the required stand-alone tables in QGIS.

**Comment by stdavis** [comment]
I'm going to close this issue as it appears that Jessie has been able to successfully edit data in the appropriate tables. Here's what the geometry looks like this morning:
![image](https://user-images.githubusercontent.com/1326248/191049099-7feed62c-3679-4dab-9cfd-fa6e093ec1bd.png)

@jshapiro49 Would you like me to remove the two test polygons that I had in that table?
