### ISSUE TITLE
Add Google Maps Link to Notification Email

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#183]
From Jessie:
>If it's possible to link the lat/lon to google maps, that would be great. Otherwise, the lat/lon in the email body would be sufficient.

It's probably safest to just do both. This kind of eliminates the need for the notification map. We could probably remove it.

**Comment by nathankota** [comment]
agreed
> It's probably safest to just do both. This kind of eliminates the need for the notification map. We could probably remove it.

**Comment by stdavis** [comment]
- [ ] add link to google maps using lat/long
- [ ] remove notification map (we'll still keep the remix app around for the admin stuff in the future)

**Comment by steveoh** [comment]
remix app!?

**Comment by nathankota** [comment]
validated
