### ISSUE TITLE
Unable to submit saved route/report 

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#185]
From Blair. Experienced the issue on an iPhone 11.

>  I ran into an issue the other day where I tried to submit a report but wasn't logged in. After logging in, I still have the unsubmitted report, but I'm not able to submit the report. I've tried multiple times but still can't submit the report. Any thoughts?

> Here is some more background on the issue...I had the app open and was able to log a report. I then started a track and created a report before ending the track. The app asked for me to login to submit the report, which I didn't do at that time (I logged in a couple hours later that night). After I logged in, I tried to submit the pending report and the screen stayed the same and the report was never submitted (screenshot attached - Submit 1 and 2). I've relogged in multiple times since then and the app still says I have an unsubmitted report, but every time I try to submit the report it never gets submitted. I've also tried to view the report I created in the track and it never loads the report (screenshot attached - Report 1).

When asked about how the app was initially opened to start collecting the route/report:

> I tapped the app icon and was taken to the map screen. It didn’t ask me the role question, and the login only came up after I had collected a few points and tracks.

#### "Submit 1" image
![Submit 1](https://user-images.githubusercontent.com/15659642/182960032-1e63f6d0-6de1-48ad-a82a-f47c7c73caca.png)

#### "Submit 2" image
![Submit 2](https://user-images.githubusercontent.com/15659642/182960050-1a0335c5-e341-4dba-9aae-7225fafd62cd.png)

#### "Report 1" image
![Report 1](https://user-images.githubusercontent.com/15659642/182960147-1eded5a9-aa14-471b-940d-c3214b0ae1fd.png)

**Comment by nathankota** [comment]
Additional info from Blair:

> I went out and tested the app again last weekend and tried to simulate the issue I had a few weeks ago. The problem seems to occur when trying to submit a route or pickup when I was out of cell coverage. The points/routes are saved in the que as unsubmitted, but I haven't been able to submit them despite logging in multiple times. If I started a route and went out coverage, or began a route when out of coverage, I was still able to submit the route if I ended the route in cell coverage. I was never able to submit a pickup if I did it while out of coverage. Maybe that will give some additional insight into the problem.

**Comment by stdavis** [comment]
I was unable to reproduce this in development. I'll test it again after I cut a new release build.

**Comment by nathankota** [comment]
I have not experienced this issue, and it seems to work fine now. I am going to close this issue and if Blair encounters it again while testing, we can reopen or start a new issue.
