### ISSUE TITLE
Prevent routes with no polyline geometry from being submitted.

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#189]
It causes the submission to never be successfully submitted.

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/191063647-e2f1745d-e467-4509-8b88-d0a1a9f0bd3a.png)

**Comment by nathankota** [comment]
@stdavis is the scenario below supposed to generate the error message and disallow route submission?

- Started tracking
- Did not move and stopped route seconds later
- Route submitted and is in My Reports

![Screenshot_20221013-093501](https://user-images.githubusercontent.com/15659642/195642130-10fb2bda-7697-49ec-a24d-0a217506a6b9.png)

**Comment by stdavis** [comment]
Yes it is supposed to prevent the route from being submitted if there is truly no tracking locations. I'm guessing that your phone reported more than one location even though you didn't move. We could add a minimum route length at some point. This was really to prevent the app from getting into an infinite loop of not being able to submit.

**Comment by nathankota** [comment]
Thank you for the explanation. I agree that we call it good, and I will add an "enhancement" for minimum route length consideration.
