### ISSUE TITLE
App Store Description/Promotional Text

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#195]
We will need text for the following entries in the app stores:

## Apple App Store

- [x] Promotional Text
- [x] Description

![Image](https://user-images.githubusercontent.com/1326248/195448158-5d94066c-3bed-4338-a94f-ad3345688f74.png)

![Image](https://user-images.githubusercontent.com/1326248/195448185-52cd18e0-7086-46ae-8c52-63226d01f2f3.png)

## Google Play Store

- [x] Short description
- [x] Full description

![Image](https://user-images.githubusercontent.com/1326248/195448408-50449ca8-bcaf-4807-bb88-9432d347c843.png)

**Comment by nathankota** [comment]
@jshapiro49 Can you and Blair provide the text that you'd like to include in the app store descriptions?

**Comment by nathankota** [comment]
@stdavis Jessie and Blair are interested to know if these text descriptions can be changed easily in the future, if needed.

### Short description and promotional text
Report animals involved in Utah vehicle collisions. 

### Description and Full Description
The Utah Wildlife-Vehicle Collision Reporter (WVCR) is a smartphone-based system for reporting animals involved in vehicle collisions. The WVCR collects information on carcass location, species, gender, age class of the animal, and photo documentation. Submissions are live-fed into a database that notifies Utah Department of Transportation (UDOT) contractors and Utah Division of Wildlife Resources (UDWR) employees of animal reports by using GIS to collect additional information on highway and management regions. The data collected through the WVCR will allow the UDWR and the UDOT to reduce wildlife-vehicle collisions and make highways safer for drivers and wildlife.

**Comment by stdavis** [comment]
A new version for the Apple App Store must be pushed to update the description, but you can edit the promotional text anytime.

For the Google Play store, it appears that we can edit either field at any time.

**Comment by stdavis** [comment]
I've got these updated in both app stores.
