### ISSUE TITLE
Rename app as "Utah Roadkill Reporter"

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#203]
In both app stores, and in the app itself.

From Blair:
_After some additional discussion, we would like to change the name to "Utah Roadkill Reporter". And that's our final answer!  I think this will make the app easier to find and reduce the confusion around acronyms._

User-facing (highest priority, required for new app submission):
- [x] Request new DNS: roadkill-reporter.utah.gov
- [x] Update App Name in Google Play Store
- [x] Update Feature Graphic for Google Play Store
- [x] App description in apple store
- [x] App description in google play store
- [x] Website secret values
- [x] Staging Build
- [x] Production Build
- [x] Splash Screen
- [x] Welcome Screen
- [x] wvc-dnr-dwr-notify@utah.gov
- [x] Store screenshots for welcome screen (google play)
- [x] Store screenshots for welcome screen (apple)
- [x] facebook app name and link to website
- [x] apadmin app name
- [x] App name in GCP Credentials config
- [x] SendGrid email templates
- [x] [Apple App Store Name](https://appstoreconnect.apple.com/apps/1566659475/appstore/info)

Internal:
- [x] Google Play Testing Group Name
- [x] Development Build

After successful release:
- [x] landing page app store links
- [x] Request removal of wildlife-collisions.utah.gov DNS

**Comment by stdavis** [comment]
DNS request: `INC1744671`
