### ISSUE TITLE
Redirect old mobile site to the new website

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#219]
@nathankota Let me know when the client wants this to be done.

**Comment by nathankota** [comment]
redirect
https://mapserv.utah.gov/wvc/mobile/
to
https://roadkill-reporter.utah.gov/

**Comment by stdavis** [comment]
It would probably be better to redirect them to their experience builder website. It has a bunch more content than our landing page.

**Comment by nathankota** [comment]
> It would probably be better to redirect them to their experience builder website. It has a bunch more content than our landing page.

Client agrees. Edited my comment above to reflect that. They have sent a notification to their agency user group to stop using the old site by January 15th. I'll set a reminder for this for the 16th.

**Comment by nathankota** [comment]
/remind us to do the redirect on January 16th, 2023

**Comment by nathankota** [comment]
/remind us to do this on January 16, 2023

**Comment by stdavis** [comment]
After that last bug report from a contractor that can't get the new app to work and is falling back to the old one, we may want to hold off on this...

**Comment by nathankota** [comment]
Agreed, let's hold off.

**Comment by stdavis** [comment]
https://mapserv.utah.gov/wvc/mobile now redirects to https://experience.arcgis.com/experience/9c34ea0968e940ac8b3fdb2d61a19280/page/Home/?views=View-16%2CTrack-Route%2CRoute-tracking%2CInstall.

Remember that https://mapserv.utah.gov/wvc/desktop is still a thing. Not sure if you want to deprecate that as well.
