### ISSUE TITLE
Add verbiage to carcass report notification

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#222]
As a public user submitting a carcass report, I would like some information on the `Success!` notification about when a pick up of my reported carcass might happen, to manage my expectations. Add the sentence:
_We appreciate your patience while we work to schedule the removal of the animal._

![Screenshot_20221214-102707](https://user-images.githubusercontent.com/15659642/207674979-74612504-0885-4d9a-9bf7-864dbb347630.png)

**Comment by steveoh** [comment]
Is there be a notification somewhere to not use the app while driving?

**Comment by nathankota** [comment]
> Is there be a notification somewhere to not use the app while driving?

No. That should happen earlier than this. New issue coming for it.

**Comment by stdavis** [comment]
@nathankota This is available for testing in the staging app in build 594.

**Comment by nathankota** [comment]
looks good in build 595
