### ISSUE TITLE
Exit Report feature earlier

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#223]
Once I tap `Report` I cannot cancel and discard the report until after I set a location. I would also like to be able to cancel my submission at each of the first two steps:

1. When selecting the type of report

![image](https://user-images.githubusercontent.com/15659642/207679630-5fff1542-ec5c-4e40-a930-9852cbe76180.png)

2. When setting the location

![image](https://user-images.githubusercontent.com/15659642/207679792-21a8b509-a71f-4660-9bbf-7e6c6de01f25.png)

**Comment by stdavis** [comment]
Funny story, I had a cancel "x" button in the setting location popup and Daniel asked me to remove it. :)

**Comment by stdavis** [comment]
![Image](https://user-images.githubusercontent.com/1326248/208209605-93128a98-5913-4109-8fa2-e8cb0120bff3.png)



![Image](https://user-images.githubusercontent.com/1326248/208209618-30a06bdb-d9a0-4e83-8d1c-a6f30110f194.png)

**Comment by stdavis** [comment]
@nathankota This is available for testing in the staging app in build 595 (may require an over-the-air update).

**Comment by nathankota** [comment]
> Funny story, I had a cancel "x" button in the setting location popup and Daniel asked me to remove it. :)

Doh! I think it might be frustrating for people to not be able to cancel before they get all the way to the report page. This looks good, thank you.
