### ISSUE TITLE
Add notification somewhere to not use the app while driving

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#224]
Is there a notification somewhere to not use the app while driving?

_Originally posted by @steveoh in https://github.com/agrc/roadkill-mobile/issues/222#issuecomment-1352072146_

**Comment by steveoh** [comment]
Unsure on the wording but it could link to https://www.dmv.com/ut/utah/distracted-driving-laws

ChatGPS says,

> Using your mobile phone while driving can be extremely dangerous and is against the law in Utah. Distracted driving significantly increases the risk of accidents and can lead to serious consequences. It's crucial to prioritize safety on the road by refraining from using this app while behind the wheel. Please remember that your focus should always be on the road and your surroundings to protect both yourself and others.

**Comment by stdavis** [comment]
@nathankota Did, you or Blair ever figure out where this should go in the app? I'm hoping that it's not in a popup that shows up ever time the app is opened. Maybe text on the new user registration page?

**Comment by nathankota** [comment]
Keep it simple for now and only include on the new user registration page.

**Comment by stdavis** [comment]
![Image](https://github.com/agrc/roadkill-mobile/assets/1326248/86fab08d-bde1-425c-9f12-a6d76b471d5e)

**Comment by nathankota** [comment]
I validated this. I'm closing for now, and if Blair wants any changes to the text we can open a new issue.
