### ISSUE TITLE
Decrease tracking vertices

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#234]
>Hello, this is Ryan Sanschagrin, the worker from Grand Junction under Epix Enterprises. Tom Stanley informed me that you would like more specifics about my phone and how I use the app, so here goes.
I use a Cricket Dream 5G from Cricket with Android version 11. Thus far I have had 2 times where I have had issues and I have suspicions as to the cause but nothing concrete. 
What I have been doing is upon reaching the Utah and Colorado border I pull over and activate tracking, then travel through all the routes I was assigned, then upon reaching the border go to deactivate tracking and report the route. That is the time at which I run into the issue.
On Friday the 20th, when I went to report, the app became unresponsive and then suddenly shutdown. When I brought the app back up it had lost the route I just did and so I could not make the report.
On Tuesday the 24th, when I went to make my report it was constantly switching between loading and showing the map, but the route tracking was lost. Interestingly, it was quite difficult to even shut the app down as it would immediately load again, even after a force stop.
I do run other apps along with it, specifically the Spotify app for music during the drive and occasionally the Google maps if I'm not sure of the turn I have to make or need to meet Tom at a specific place.
The suspicions I have are that the app becomes unstable with continuous use over a long time, or Google maps being used simultaneously causes issues, or losing service for long enough causes problems, although the last would only account for my last trip on the 24th.
I hope any of this information is helpful and would be thankful for any advice as to why the app is acting up. If you have any questions, feel free to contact me.

I think that the tracking frequency should be lowered so that there are fewer vertices being collected.

**Comment by stdavis** [comment]
This was released in v3.0.5 (604)

**Comment by steveoh** [comment]
is there a way to simplify the vertices as they are collected to reduce the complexity of the line?

**Comment by stdavis** [comment]
Yes, I used cheap-ruler to filter out any new points that are within 15 meters of the last point. https://github.com/agrc/roadkill-mobile/commit/0ce7e521dc06bf7a428bf61d921f91edd014808b
