### ISSUE TITLE
Privacy policy - data deletion requirement for facebook

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#247]
Asked Blair for DWR AG help with:

> Your action is needed by 2023-03-13 02:00:00 PDT for: Utah Roadkill Reporter (184357517052916)
> From: Facebook <[case++aazqjz2tmtpbiw@support.facebook.com](mailto:case%2B%2Baazqjz2tmtpbiw@support.facebook.com)>
> Date: Mon, Feb 27, 2023 at 3:38 AM
> Subject: Your action is needed by 2023-03-13 02:00:00 PDT for: Utah Roadkill Reporter (184357517052916)
> To: Utah Roadkill Reporter <[utah-roadkill-reporter-notify@utah.gov](mailto:utah-roadkill-reporter-notify@utah.gov)>
> 
> Hi,
> 
> In working to create a great Platform experience for everyone, we ask developers to ensure the apps they build comply with our Platform Terms and Developer Policies. Your app Utah Roadkill Reporter  (AppId: 184357517052916) doesn't comply with the following:
> 
> 
> Platform Terms 4.b: Your privacy policy must comply with applicable law and regulations and must accurately and clearly explain what data you are Processing, how you are Processing it, the purposes for which you are Processing it, and how Users may request deletion of that data.
> 
> During testing, we found that your privacy policy doesn’t explain how users can request data deletion. Update your privacy policy to include this information before you submit an appeal.
> 
> For more information, visit:
>   - Developer Policies: https://developers.facebook.com/devpolicy
>   - Platform Terms: https://developers.facebook.com/terms
> 
> Please make the requested changes by 2023-03-13 02:00:00 PDT.
> 
> We encourage you to request screenshots from us to determine the violating behavior. You can also request up to two extensions if you need additional time to gather information. Please note that extensions cannot be unbounded, so it is important that you act promptly to address the issues.
> 
> Let us know when you've updated your app by replying directly to this email. To guarantee that we receive your response:
> - Ensure you are emailing from the contact email registered in App Dashboard.
> - Respond directly to this email and include our email address in the “to” field.
> - Do not change the subject line or include any additional emails in the "cc" field.”
> 
> If we do not hear back from you, your app will be subject to enforcement. If you have outstanding questions, respond here and we'll do our best to help.
> 
> Thanks,
> 
> Meta Developer Operations Team

**Comment by nathankota** [comment]
/remind me in one week if I haven't heard back from Blair

**Comment by stdavis** [comment]
@nathankota This is ready for testing in staging via over-the-air update (v3.0.6 (607)).

**Comment by nathankota** [comment]
This looks great to me in the staging app. Is the next step to send screenshots or whatever from staging to Facebook then wait for their response? And should I keep this issue open, or close it? I'm happy to do whichever you prefer there.

**Comment by stdavis** [comment]
The next step is to push to production and respond back to Facebook and have them look at it again. I'd prefer to keep this issue open until they are happy. I'll take things from here. Thanks!

**Comment by nathankota** [comment]
@stdavis I couldn't quite tell if the most recent response from FB/Meta was acceptance of the fix?

**Comment by stdavis** [comment]
Neither could I. ;) But I haven't heard anything from them since and everything is green on the app dashboard. So I'm thinking that we are out of the woods.

**Comment by nathankota** [comment]
One more sentence added to the end of the [privacy policy doc](https://docs.google.com/document/d/17Sc_I4QsuYGqyhKS7rce6MmkKuAyq0rJ8H70dLhNL64/edit). For full user data deletion client want to see if an email to the [utah-roadkill-reporter-notify@utah.gov](mailto:utah-roadkill-reporter-notify@utah.gov) satisfies FB's requirements.

**Comment by stdavis** [comment]
I added the extra line to the privacy policy page, recorded a new video, and resubmitted it.

**Comment by stdavis** [comment]
They seem happy?
![image](https://user-images.githubusercontent.com/1326248/231789350-ba76f9ad-0c86-4a76-bcc8-7b3fe2664ad4.png)
