### ISSUE TITLE
Stub out new project structure

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#25]
- [x] React Native app
- [x] Cloud Run for interacting with DB
- [x] Auth - Does this need to be specific to this project?
- [ ] Notifications services
- [x] GCP Projects

Could this work all within the same repo?

**Comment by nathankota** [comment]
Is auth different between Utah login (internal users) and other providers (e.g. google and facebook) for public users?

**Comment by stdavis** [comment]
Yes, there will have to be different code written to handle both types of providers.

**Comment by stdavis** [comment]
I think that the project structure is good for now. I can add notification services later.
