### ISSUE TITLE
Deprecate old roadkill desktop app

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#251]
- [x] Porter issue (https://github.com/agrc/porter/issues/235)

Roadkill-web and the desktop/mobile app
https://mapserv.utah.gov/wvc/desktop
https://github.com/agrc/roadkill-web
http://test.mapserv.utah.gov/wvc/mobile or desktop (no longer there with new test server)

**Comment by nathankota** [comment]
Pause on this until we figure out what needs to be done with data migration from old app database.

**Comment by nathankota** [comment]
/remind me on Monday, April 10, 2023

**Comment by stdavis** [comment]
Still working on the migration. Hopefully, it will be done by today...
