### ISSUE TITLE
Secret name inconsistency

### ISSUE THREAD

**Issue by steveoh** [agrc/roadkill-mobile#257]
https://github.com/agrc/roadkill-mobile/blob/0069ed5944d8e83e930a06a5b1dd3449b3d1d13d/src/palletjack/src/roadkill/main.py#L42-L54

This is referencing your secret mount incorrectly

https://github.com/agrc/roadkill-mobile/blob/0069ed5944d8e83e930a06a5b1dd3449b3d1d13d/.github/actions/palletjack/deploy/action.yml#L44

Your secret is mounted as `/secrets/app/secrets.json`

**Comment by stdavis** [comment]
Good catch. Thanks.

**Comment by stdavis** [comment]
This has been fixed.
