### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#26]
Make sure to separate public data submissions from collector reports

- [x] create initial database from design
- [x] create cloud SQL instance
- [x] Figure out how to give the client access (e.g. cloud SQL proxy or open IP)

**Comment by nathankota** [comment]
### Feature Classes

- Reported carcass points
- Retrieval location points
- Tracks
- Service Areas

### Tables

- User table (retrievers only (contractors+agency employees))
- Employer table (to relate to records in user table)

**Comment by stdavis** [comment]
Jonathon Foster says that our only option for allowing access to the cloud SQL database is for clients to run [auth proxy](https://cloud.google.com/sql/docs/postgres/sql-proxy).

Keaton suggested using [federated queries](https://cloud.google.com/bigquery/docs/cloud-sql-federated-queries) to give them access to the database in big query. Not sure which the client prefers. We'll have to ask them. @nathankota Do you want to start this conversation? It might be best to see how they are interacting with the data in the new collars system. Then maybe we can work up something that they are already familiar with.

**Comment by nathankota** [comment]
(Question about preferred method of db access posed to DWR staff)

**Comment by nathankota** [comment]
/remind me to check on this Monday, August 2, 2021

**Comment by nathankota** [comment]
/remind me to check on this August 2, 2021

**Comment by nathankota** [comment]
> Jonathon Foster says that our only option for allowing access to the cloud SQL database is for clients to run [auth proxy](https://cloud.google.com/sql/docs/postgres/sql-proxy).
> 
> Keaton suggested using [federated queries](https://cloud.google.com/bigquery/docs/cloud-sql-federated-queries) to give them access to the database in big query. Not sure which the client prefers. We'll have to ask them. @nathankota Do you want to start this conversation? It might be best to see how they are interacting with the data in the new collars system. Then maybe we can work up something that they are already familiar with.

They prefer the Keaton-recommended federated queries option. Is that going to be okay?

**Comment by stdavis** [comment]
Yes! I believe that the federated queries option is the easiest option. There is a database up and running in `ut-dts-agrc-roadkill-dev` that they are welcome to point their federated queries at. Let me know if they need anything else from me to access it.
