### ISSUE TITLE
Offline Data Collection

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#28]
Add support for offline data collection, storage, and syncing to the server when online again.

[There should be some sort of indication to the user from outside of the app that there are unsubmitted reports such as a bubble on the app icon](https://github.com/agrc/roadkill-mobile/issues/79). 

* [x] Daniel would like the indicator to show the number of cached reports.

Bonus points for automatically submitting reports in the background once the device has a network connection again.

**Comment by nathankota** [comment]
validated, except for the app icon indicated there are pending reports, ref #79
