### ISSUE TITLE
UtahID Sign In Prompting too Frequently

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#287]
As reported by Jessica Kinross:
>Contractors have mentioned having to sign in and get a code (I assume go through the multi-authentication) multiple times when they are on a route, it appears going out of service requires them to log in again and this takes alot of time to wait for the code and sometimes they can't get logged back in.. Is there a solution for this? Might it help solve this if they are recording their route so it is keeping them active in the system??

**Comment by nathankota** [comment]
implemented in v3.0.7
