### ISSUE TITLE
Offline Reports Stuck in Outbox

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#288]
As reported by Jessica Kinross:
>Some contractors are showing multiple reports in their outbox and they aren't sure if they have been submitted or not. We wonder if the issue the other contractor is having with the photo could be the issue that the reports aren't properly loading to be submitted. How do we help make sure all the reports in the 'outbox' are submitted? in other words, how do we help clear the outbox.

I'm not sure how we reproduce this. Maybe the fix for #286 will take care of it.

**Comment by stdavis** [comment]
I belive that I've made some changes to prevent this from happening in the future. But I'm not sure how to fix the reports currently stuck in the app. I suspect that they are empty and contain no data. I suggest uninstalling the app, restarting their phone and then reinstalling the app to clear them out.

**Comment by nathankota** [comment]
has this been communicated to the roadkill team, or do we still need to do that?
> I believe that I've made some changes to prevent this from happening in the future. But I'm not sure how to fix the reports currently stuck in the app. I suspect that they are empty and contain no data. I suggest uninstalling the app, restarting their phone and then reinstalling the app to clear them out.

**Comment by stdavis** [comment]
No, it has not been communicated since I haven't yet pushed the new release that this fix is contained in.

**Comment by nathankota** [comment]
implemented in v3.0.7
