### ISSUE TITLE
Update public report submission message

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#295]
Here is what the current message says after a member of the public submits a report:
 
> Your report has been submitted and a notification has been sent to remove the animal. We appreciate your patience while we work to schedule the removal of the animal.

Updated language:

> Your report has been submitted and a notification has been sent to remove the animal. In some instances the animal may not be removed. We appreciate your patience while we work to schedule the removal of the animal.

**Comment by stdavis** [comment]
This is an easy fix. I'll include it in the next release.

**Comment by stdavis** [comment]
I just pushed an update to staging with this update: v3.0.7 (636)

**Comment by nathankota** [comment]
validated
