### ISSUE TITLE
Mockup mobile application

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#30]
Mock up mobile app layout and functionality.

The [original specs doc](https://docs.google.com/document/d/16PkYtJjh3p9F_cjL8qQfoe5wVfrZweRayTHUZRJaOMQ/edit) will be helpful with this.

**Comment by nathankota** [comment]
These will eventually be on the [Lucid board](https://lucid.app/lucidspark/0d71024b-7328-4552-ac0a-0f8d093a5e08/edit#).

**Comment by stdavis** [comment]
Are you doing the mockups or me? Or maybe the client?

**Comment by nathankota** [comment]
I will work with them in our "exploratory" phase to build the mockups, once we have the user stories/requirements refined a bit more.

**Comment by nathankota** [comment]
Some similar apps are:
[Roadkill TAS](https://play.google.com/store/apps/details?id=com.thundermaps.roadkilltas&hl=en_AU
)
[Roadkill Spotter ](https://play.google.com/store/apps/details?id=com.spotteron.roadkill&hl=en_AU)
[Roadkill USA](https://play.google.com/store/apps/details?id=com.spotteron.roadkill&hl=en_AU)

**Comment by nathankota** [comment]
@stdavis do you think we're okay to close this issue?
