### ISSUE TITLE
Simplify Repeat Submission Confirmation

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#309]
From a user:
>The biggest bug is when I'm done marking where the deer is and after confirming the age and sex.  I'm ready to submit the report, but a popup comes up and asks me if I want to cancel the report or if this is a resubmission.  Even though it's not a resubmission in order to post it I have to check that it is.

To simplify the process, we decided to remove the confirmation dialog altogether and just show the "Please understand that it may take up to two weeks for a reported animal to be removed." text directly on the form if the user toggles the repeat switch to "Yes".

**Comment by nathankota** [comment]
I tested this today on staging and did not experience any hiccups or issues, so I am confident in validating that this is working.
