### ISSUE TITLE
Vehicle Tracking

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#31]
From the [Spec Sheet](https://docs.google.com/document/d/16PkYtJjh3p9F_cjL8qQfoe5wVfrZweRayTHUZRJaOMQ/edit):

![image](https://user-images.githubusercontent.com/1326248/114754053-61771400-9d15-11eb-8856-cc95daee0d88.png)

Possible solution via expo:
https://docs.expo.io/versions/latest/sdk/task-manager/#example
https://docs.expo.io/versions/latest/sdk/location/#background-location-methods

[Mockups](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457360911698528&cot=14)

**Comment by stdavis** [comment]
Latest mockups from Daniel:
[Tracking Function.pptx](https://github.com/agrc/roadkill-mobile/files/7884400/Tracking.Function.pptx)

My feedback which he was good with:
>I wonder if there should be some sort of visual cue to distinguish between these two states:
>1 - a route has been started but paused
>2 - no route has been started

>Maybe the "Track" button should have three different colors; one for each of the states above and then another one for actively tracking.

>It seems counterintuitive to me for the user to have to tap on “Finish and Submit Route” to see the stats for the current route. I wonder if those should be moved to the dialog with the pause, finish, and cancel buttons.

**Comment by nathankota** [comment]
FYI - I put the tracking mockup in https://docs.google.com/presentation/d/1qFQvVkymcOOIlPqOusVa7tLbkXWqtft4/edit

**Comment by nathankota** [comment]
validated
