### ISSUE TITLE
Menu won't open

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#311]
**app:** production
**version:** 3.0.7
**user:** logged in as public user on state device, and logged in as state agency user on personal device
**issue:** open app and tap on menu/folder icon in upper left corner and the menu does not open

**Comment by nathankota** [comment]
staging app version 3.0.9
runtime version 3.1.0
build number 643

This issue was no longer detected. Do you want me to close this issue or wait for a prod release?

**Comment by stdavis** [comment]
Let's wait for a prod release just to be sure.
