### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#32]
See [Development Plan](https://docs.google.com/document/d/1ov5tFX-dcNkqvn7aCzUCsaMyhyBOdDq5ECVPCN-0o54/edit#heading=h.ywc5zjchc7ek) for tech specifics.

Support for UtahID and two other popular oauth providers such as google, facebook, etc.

Roles
1. Reporter - 
    - anyone can report an animal

2. Agency 
    - Utah ID required
    - Remove carcasses
    - Submit a carcass observation report without removing
    - Not required to submit route with removal data

3. Contractor 
     - Utah ID required
     - Start route and collect removal records along the way
     - Required to submit route data with carcass removal data

4. Admin - 
    - All Agency user features plus user management, etc

They are OK with using ApAdmin for backend user management. - Yes

**Comment by stdavis** [comment]
@nathankota Another question for the client...
There will obviously be some sort of request access/approval process for retrievers and admins. Do they want the same thing for public reporters? Or can anyone just sign up and submit reports without any human approval process?

**Comment by nathankota** [comment]
I had the same questions, and will ask them early on. I know Steve is using jumpcloud for the UIC app, which may also apply here if they want to skip human approval for public users (?).

**Comment by steveoh** [comment]
What is jump cloud?

**Comment by stdavis** [comment]
> public users of the UIC app (once they sign up for a Utah ID)

I don't think that the client wants to ask the public to sign up for a UtahID account. This is where the two other oauth providers come in (Google/Facebook).

**Comment by nathankota** [comment]
Correct - no UtahID for this app. I thought the flow might be applicable for both apps (UIC and WVC), although not using UtahID here. I just continue to put my foot in my mouth in this comment thread.

**Comment by nathankota** [comment]
`enhancement` label added due to the separation of the Retriever/Remover role into Agency and Contractor

**Comment by stdavis** [comment]
This might be helpful: https://therootcompany.com/blog/popular-signin-uis/
