### ISSUE TITLE
Implement Service Workers as Replacement for AppCache

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#4]
Looks like the [application cache](https://www.fxsitecompat.com/en-CA/docs/2016/application-cache-support-will-be-removed/) will be removed at some point in FireFox. However, I can't image that they will remove it before Safari [has implemented it](https://webkit.org/status/#specification-service-workers). Chrome seems [headed in this direction as well](http://stackoverflow.com/a/28806487/4166171) but hasn't started anything formal yet other than for [insecure origins](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/UKF8cK0EwMI).

David Walsh looks like he has a [good article](https://davidwalsh.name/offline-recipes-service-workers) on it.

**Comment by stdavis** [comment]
This project may be helpful: https://github.com/GoogleChrome/sw-helpers/tree/master/projects/sw-appcache-behavior

**Comment by stdavis** [comment]
Another possibly useful resource: https://blog.formpl.us/a-simple-guide-to-taking-a-web-page-offline-using-service-workers-f4c42e7b4ada

Also, I believe that Service Workers shipped with iOS 11.3 recently so it may be time to think about working on this.

**Comment by stdavis** [comment]
Another possibly useful article: https://alistapart.com/article/going-offline

**Comment by stdavis** [comment]
Someday I'll get to this. Here's another possibly helpful option: https://developers.google.com/web/tools/workbox/

**Comment by nathankota** [comment]
@stdavis 
Is this a necessary fix for the app to operate properly in its current state, and could it be done within the maintenance agreement amount ($5k?)? I'd like to approach Ashley and Daniel Olson about a complete rewrite, but not sure where this fits in.

**Comment by stdavis** [comment]
I think that it could be done within the maintenance money but it would take the majority of it.

**Comment by steveoh** [comment]
closed by #10 

There might be some further uses of the service worker for uploading pickups. 

checkout [background sync](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync)
