### ISSUE TITLE
App Architecture Diagram

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#41]
Build a diagram of the backend stuff. DWR is especially interested in this and understanding how to access the data from the db for things such as statistical modeling and other data analysis.

Put it in the [lucid spark for this project](https://lucid.app/lucidspark/0d71024b-7328-4552-ac0a-0f8d093a5e08/edit#)

High-level, more worried about how to get at the data.

**Comment by stdavis** [comment]
@nathankota Is the simple chart on the lucid graph what you were looking for with this issue?

**Comment by nathankota** [comment]
(I'm fine with it, but checking in with client(s) to confirm it suits their needs)

**Comment by nathankota** [comment]
![image](https://user-images.githubusercontent.com/15659642/117170816-9102c480-ad87-11eb-896b-081dab8e7e1a.png)
