### ISSUE TITLE
Capture Animal Photos

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#42]
Add the ability to capture an image of the animal.
>One required image, and they would like to capture the image location from the image properties, so they know if contractors are taking pics at the actual carcass location, or in the back of their truck in a parking lot somewhere else (apparently that happens)

I'm not sure on getting the coordinates from the image but I can look into it.

@nathankota This is for retriever submissions, not public reports, correct?

**Comment by nathankota** [comment]
Yes, that is for retrievers, but I wonder if they want the option for public to submit an image, although not required. I will be generating a list of questions for our next meeting, and will put this on there.

**Comment by nathankota** [comment]
Reporter image submission will be optional, but verbiage in the UI will encourage them to submit.

**Comment by nathankota** [comment]
validated
