### ISSUE TITLE
Splash Screen & Icons

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#43]
https://docs.expo.io/guides/app-icons/#design

**Comment by stdavis** [comment]
@nathankota Do we want to ask the design group to help with these? We didn't include that in our estimate. Otherwise, maybe @steveoh and I can hack something together on our own.

**Comment by nathankota** [comment]
Reminded agencies today that these elements are still needed.

**Comment by stdavis** [comment]
Closing in favor of #114
