### ISSUE TITLE
Research: Cloud db to BigQuery

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#47]
What is the possibility of setting up a cloud function or something similar to wire up the cloud sql db to bigquery and have the data accessible in real-time?

**Comment by nathankota** [comment]
I'm sure communicating with Steve and Keaton will also produce some ideas.

From Jessie:
> Instead of wiring up a cloud function to load data into BigQuery, we can explore using a Cloud SQL federated query and either create a view or run it on a cloud scheduler.

**Comment by stdavis** [comment]
Sounds like they may be able to handle this on their own as long as we store the data in Cloud SQL? I'll ask Keaton about it at some point as well.

**Comment by nathankota** [comment]
Yes, I wasn't sure how much they were willing to try on their own, or wanted some suggestions. Chatting Keaton up sounds good to confirm their strategy, or come up with others. Whenever the cloud sql db is instantiated, could we provide them with credentials so they can test their ideas?

**Comment by stdavis** [comment]
> Whenever the cloud sql db is instantiated, could we provide them with credentials so they can test their ideas?

Yes, I'll make sure to do that.

**Comment by stdavis** [comment]
Confirmed from Keaton that federated queries are the way to accomplish this without having to copy data: https://cloud.google.com/bigquery/docs/cloud-sql-federated-queries
