### ISSUE TITLE
Steps for first Production Release of v3

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#50]
- [x] complete and upload production builds
- [x] [submit](https://appstoreconnect.apple.com/apps/1566659475/appstore/ios/version/inflight) iOS app for apple app store review
    - [x] set app store submission to latest build
	- [x] screenshots (6.5": iPhone 13 Pro Max)
	- [x] description text (#195)
	- [x] verify production app store listing
- [x] [submit](https://play.google.com/console/u/1/developers/6377537875100906890/app/4972434106866476517/main-store-listing) Android app for google play store review
	- [x] screenshots
	- [x] description text (#195)
	- [x] verify production app store listing
- [x] make `production` branch the default branch and rename `main` to `v2`
- [x] create missing secrets for `Production` environment in repo
- [x] create missing `PRODUCTION_*` secrets in [EAS](https://expo.dev/accounts/agrc/projects/wildlife-vehicle-collision-reporter/secrets).
- [x] run terraform in prod workspace
- [x] fill in run URL in `src/front/.env.production`
- [x] add delete user content page for [facebook sign in requirement](https://developers.facebook.com/apps/184357517052916/settings/basic)
- [x] make facebook app public so that it allows anyone to login
- [x] Request `wildlifecollisions.utah.gov` DNS and update in `gcp-terraform/roadkill/main.tf`
- [x] copy identify images from dev to prod bucket
- [x] migrate and cull data new database:
    - [x] organizations
    - [x] users
    - [x] users_have_notification_areas
    - [x] notification_areas
    - [x] species
- [x] push latest versions of back and website to prod
- [x] test production builds
    - [x] remove test data

**Comment by stdavis** [comment]
@nathankota It's time to start thinking about what the public DNS for this app should be. I'm guessing that they don't want something like `roadkill.ugrc.utah.gov`. Maybe they want something off of UDOT like `wvcreporter.udot.utah.gov`? Or `wvc.utah.gov`? Or something else?

This DNS is going to be used for the notification map and probably the admin website in the future. It could also host some generic landing page that links to the app store entries for the mobile app.

**Comment by stdavis** [comment]
I just noticed `wildlifecollisions.utah.gov` on discover. Did we already make this decision? It doesn't point anywhere at the moment but if this is what it should, I'll go ahead and start the process of registering a DNS...

**Comment by nathankota** [comment]
I notified them that we will go ahead and register the `wildlifecollisions.utah.gov` DNS.

**Comment by nathankota** [comment]
> I notified them that we will go ahead and register the `wildlifecollisions.utah.gov` DNS.

Did we do this?
