### ISSUE TITLE
Fill out Archer Security Form(s)

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#55]
I believe that this is required for app deployment.

**Comment by nathankota** [comment]
I will get this rolling with DTS Security. They have a new system ("Archer"), which may be what we need to use instead of the 524. Good call on getting this going early on!

**Comment by nathankota** [comment]
From Robert "Ryan" Bramwell (rbramwell2@utah.gov)

> You should be able to use the same forms as last time. I assume it will be like the last one we did with Roxanne where Corrections of using the application but being developed by you. If so I'll be including Dan Cook in this email since he is over DNR which DWR is part of. He may have some additional questions.

In addition to the forms below we will need data flow and network diagrams. Examples of all of these can be found for the AP&P project [here](https://drive.google.com/drive/folders/1L__ABuRfcjcqAYVONMAwvfLPuv05npLX).

#### [Archer Assessment and Authorization Data Form](https://docs.google.com/document/d/1Gz3cNqS5z3Cx1V7-fsYv6JsmCtqo_NT8uEpWYCW588A/edit)

#### [Archer Risk Assessment Data Form](https://docs.google.com/document/d/1xrtcGkD7aSqHL5dEU5t_f7UlurLPjn6qTqyANmGPrtE/editl)

**Comment by nathankota** [comment]
/remind me of this on February 28, 2020

**Comment by stdavis** [comment]
@nathankota I'm not sure why the reminder bot got the wrong date, but I noticed that your year was incorrect...

**Comment by nathankota** [comment]
Ha! Reminder bot was correct, I was off by two years! Thanks for catching this.

**Comment by stdavis** [comment]
@nathankota Do you need my help with this?

**Comment by nathankota** [comment]
> @nathankota Do you need my help with this?

I submitted [INC1633564](https://utah.service-now.com/nav_to.do?uri=incident.do?sys_id=d49986dc877209d002637489cebb3573%26sysparm_view=ess) and shared [the diagrams](https://lucid.app/lucidchart/85fa7bb9-0dea-4684-886a-d81e3ac90092/edit?page=0_0&invitationId=inv_e0b2db56-26c1-44df-b519-e39b67117f94#) with R. Bramwell to get the Archer docs going.

**Comment by nathankota** [comment]
As far as I can tell this is complete

[RSA Archer Authorization Package](https://grc.archer.rsa.com/apps/ArcherApp/Home.aspx?workspaceId=-1&requestUrl=..%2fGenericContent%2fRecord.aspx%3fid%3d439860%26moduleId%3d494#)

[Cloud Checklist](https://docs.google.com/spreadsheets/d/1eXmcAyPG7TsRaGR54muSgsghFhLpU_Xa/edit#gid=1210683282)
