### ISSUE TITLE
Read-only access to GCP projects

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#58]
please provide the following DWR staff read-only access to ut-dts-agrc-roadkill-dev and ut-dts-agrc-roadkill-prod:

- Jessie
- Buck
- Daniel

**Comment by stdavis** [comment]
@steveoh - Do you have any opinion on whether this should be done via Terraform or manually?

**Comment by steveoh** [comment]
I would do this with terraform and roles.

**Comment by stdavis** [comment]
@nathankota You can let these DWR folks know that they should have viewer access to both the dev and prod GCP projects:

* https://console.cloud.google.com/home/dashboard?project=ut-dts-agrc-roadkill-dev
* https://console.cloud.google.com/home/dashboard?project=ut-dts-agrc-roadkill-prod

Ref: https://github.com/agrc/gcp-terraform/commit/8a7df0b7af9ec7cc17bc84d8dca5b0974a5dca3c
