### ISSUE TITLE
Decide on UI framework

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#59]
- [x] basic forms, textbox, button, radio button
- [x] notification badge
- [x] dropdown/typeahead
- [x] tabs
- [x] date/time picker
- [x] banner/notification/toast

**Comment by stdavis** [comment]
I think that UI Kitten [won the contest](https://docs.google.com/spreadsheets/d/1MBcwc43VdbPP3Zu0SvnJ4XDI4EUDECDYUJx3XtHmO94/edit#gid=0). 🐱 

Have to be honest, I'm really not a cat person. Not sure how this will go. ;)

**Comment by nathankota** [comment]
meow
