### ISSUE TITLE
Save Canceled Routes

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#65]
> When a route is canceled we still want these to be submitted to the database.

[Miro content here](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457359648854701&cot=14)

### Questions

**Database:** 
- y/n `canceled` field in `routes` table, triggered to `y` when the canceled route is confirmed in the app?

**Notification:** 
- Do we need to indicate to the user that their canceled routes get submitted? If not, can canceled routes by auto-submitted so users don't need to take any action to submit, or even know they get submitted?

**Comment by nathankota** [comment]
@stdavis This would require the `bonus points` section of #28 to be implemented?

**Comment by nathankota** [comment]
@stdavis This would require the `bonus points` section of #28 to be implemented?

**Comment by stdavis** [comment]
I've already sent this to @nathankota in chat but wanted to put it here to keep the history of this issue up-to-date:

I feel very uncomfortable sending location tracking data to our server without the user having the chance to cancel. I'm not sure that's even ethical. The user should always be in control of what data is sent to the server especially if it's location tracking data.

**Comment by nathankota** [comment]
Contacted client about eliminating this feature/requirement.

**Comment by nathankota** [comment]
Client is okay with not implementing this feature.
