### ISSUE TITLE
New User Registration View

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#66]
@nathan Do you have the latest updates on this view from our last meeting? I remember that they decided to show it to all user types (not just non-public) but that they wanted to collect different info from the different groups.

**Comment by nathankota** [comment]
I updated [this view](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457360913088222&cot=14). See the notes at the bottom for more information. Does this get the answers you were looking for?

**Comment by stdavis** [comment]
Looks great. Thanks for the quick response!
