### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#67]
Make the app accessible for Spanish speakers/readers.

**Comment by stdavis** [comment]
Just an FYI. I used GitHub Copilot to generate the translations. So there is no guarantee that they are perfect.

**Comment by steveoh** [comment]
Should we double check them with google translate?

**Comment by stdavis** [comment]
I believe that Nathan said that DNR had someone that would take a look at them. You can see them all in this file: https://github.com/agrc/roadkill-mobile/blob/staging/src/front/services/translations.json

**Comment by nathankota** [comment]
Will ask DWR to review all translations.

Found the following areas where translation is missing:

My Reports

![Image](https://github.com/agrc/roadkill-mobile/assets/15659642/791fdb84-6965-41ba-a5e0-c97144135e62)

Profile


![Image](https://github.com/agrc/roadkill-mobile/assets/15659642/0bc3326c-42f4-4422-ad38-f849c75b2c52)


About


![Image](https://github.com/agrc/roadkill-mobile/assets/15659642/2ef6dc06-4f53-437e-a316-90021828a9d1)

Logout


![Image](https://github.com/agrc/roadkill-mobile/assets/15659642/a9f5638c-4f71-49c9-ba98-168fba9fda7a)


Report > common name


![Image](https://github.com/agrc/roadkill-mobile/assets/15659642/f79b25db-c298-4dda-be79-4fbc8848b537)


Report > family


![Image](https://github.com/agrc/roadkill-mobile/assets/15659642/104e33ed-3da1-49d2-b381-1d173a56c8e1)

**Comment by stdavis** [comment]
I just pushed an update to staging with this update: v3.0.7 (636)

**Comment by stdavis** [comment]
From Jessica today:
>I got the spanish reviewed!

>Here are the comments from the reviewer: 
>The translations look great to me, however there were two lines in need of some attention. In lines 245 and 263 the word "Carcasa" should be changed to "Cuerpo." The word "cuerpo" means "carcass," but I noticed that in lines 377 and 378 the word "cadaver" is used. The word "cadaver" means corpse, I think the translation is correct, but it is worth noting that these two words can be interchangeable and may confuse some users.

**Comment by nathankota** [comment]
implemented in v3.0.7
