### ISSUE TITLE
Default Map Screen

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#72]
### [Miro mockup](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457361075379020&cot=14)
 This is the default page once I have created an account and profile, and each time I open the app thereafter. 

- [x] Basemap centered with point at device location
- [x] Hamburger icon containing the following 
    - [x] My Reports
    	- [x] notification bell for unsubmitted reports
    - [x] Profile
    - [x] Contact
    - [x] Logout
- [x] Map tools
    - [x] My location - tap to zoom to device location
    - ~[ ] Basemap selector~
- [x] "Plus" icon for adding reports (depending on user role)
- [x] Vehicle icon for tracking and managing routes - not visible for Public user role

**Comment by stdavis** [comment]
I punted the base map selector to #90 since I didn't feel like it contributed to an MVP. Let me know if the app should be switch to Hybrid by default.

**Comment by stdavis** [comment]
@nathankota Other than my #90 punt, this should be ready for verification with build >= `348`. You can test what the badge/notification looks like on the menu icon by tapping on the "+" icon. I hardwired that button to toggle the badge just for testing.

**Comment by nathankota** [comment]
It took a couple rounds of un/re-installing and logging out/in but I am finally at `348` and this is looking great.
