### ISSUE TITLE
User profile page/screen

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#73]
### [Miro mockup](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457360912639323&cot=14)

- Accessed via the hamburger icon on the default page (#72)
- Name and Email are from the OAuth provider and not editable
- Organization is only included for Contractor and Agency users - editable through this page/pane
- Contact included for all users and also editable here

**Comment by stdavis** [comment]
We are requiring public reporters to input their personal address?

**Comment by nathankota** [comment]
There was a misalignment between the two profile sections on the Miro. Thank you for catching that. Address is no longer included. Original comment edited accordingly.

**Comment by nathankota** [comment]
looks good!
