### ISSUE TITLE
Contact admin

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#74]
### [Miro mockup](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457361075759544&cot=14)

- Accessed via the hamburger icon on the default page (Default Map Screen #72)
- Opens device default email client with a pre-defined "to"address (TBD)
- Way to have the app give confirmation than an email was sent?

**Comment by nathankota** [comment]
Working with DWR+UDOT to find out what email address they'd like to use to receive messages from the app.

**Comment by stdavis** [comment]
I'd suggest creating a google group and adding dwr members to it.

**Comment by nathankota** [comment]
Google group created #75

**Comment by stdavis** [comment]
This should be available to test in build 358+.
