### ISSUE TITLE
RSA Token 2FA for UtahID users is a pain on Android

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#76]
1. Open app and tap on login with utah id.
2. Type in username and password.
3. Utah id prompts for 2fa code.
4. Switch to token app and get code.
5. Upon switching back to roadkill, the oauth webview is gone and you need to log in again. And you better be quick before your code expires and you have to start the process over again. :(

The [ServiceNow](https://play.google.com/store/apps/details?id=com.servicenow.fulfiller&hl=en_US&gl=US) app is an example of how it should work.

**Comment by stdavis** [comment]
https://forums.expo.dev/t/switching-apps-on-android-for-2fa-cause-oauth-flow-to-start-over-again/55304?u=agrc

**Comment by nathankota** [comment]
I tested this several times and it works as expected now!
