### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#77]
### [Miro](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457361643743338&cot=10)

- From the hamburger icon on the main screen please add a link to logout of the app. 
- Add a confirmation message to inhibit accidental logout. 

(Additional Miro mockup [here](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457361076292269&cot=14), but only meant to convey the idea, and not as the final design.)

**Comment by stdavis** [comment]
This should be available to test in build 358+.
