### ISSUE TITLE
My Reports - Public View

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#78]
- Click hamburger icon on main screen
- Select [`My Reports`](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457361643743338&cot=10) 
- See list of saved and submitted reports, and access to the individual reports
- The My Report screen shows ([something like this](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457359650029947&cot=14)):
    -  Species (or whatever data we end up storing if they choose the "don't know species" path)
    - Date report was submitted
    - Link to view submitted data
    - Whether report has been submitted or not, and a way to submit it

**Comment by stdavis** [comment]
This has been implemented with build 448+ except for the offline stuff. I'm punting that for now until #28.

**Comment by nathankota** [comment]
This looks good and we will consider it complete, with any changes to be included in new issues.
