### ISSUE TITLE
Unsubmitted report notifications

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#79]
If I have one or more unsubmitted reports, show some kind of notification on the app icon (if possible), the [`My Reports` link](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457361643743338&cot=10) within the hamburger (I just like writing "hamburger"), and on [My reports](https://miro.com/app/board/o9J_kmPc6Eo=/?moveToWidget=3074457359650030051&cot=14) screen.

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/160708740-73f24b7b-e9d0-4511-8403-d7e350709b96.png)
![image](https://user-images.githubusercontent.com/1326248/160708760-1289fb9a-775f-446a-99ff-d13ca0c468e8.png)
![image](https://user-images.githubusercontent.com/1326248/160708809-8bb47676-2fbc-4539-80e6-e61995c1d438.png)

**Comment by steveoh** [comment]
That's so cool! 🥇

**Comment by nathankota** [comment]
I was able to see the notification within the app in the places Scott showed above, but not on the app icon:

![image](https://user-images.githubusercontent.com/15659642/163886515-b1e6a05e-4ffe-4981-8ff4-051946d5ee24.png)

**Comment by nathankota** [comment]
☝️  @stdavis it looks like the app icon on your iOS device shows the pending reports, but my Android did not.

**Comment by stdavis** [comment]
I need to research to see if this is the way that it is or if something is broken on Android.

**Comment by stdavis** [comment]
I don't see the app icon notification on my android test device or emulator. It appears from [the Expo docs](https://docs.expo.dev/versions/latest/sdk/notifications/#:~:text=Note%3A%20Not%20all%20Android%20launchers%20support%20application%20badges.%20If%20the%20launcher%20does%20not%20support%20icon%20badges%2C%20the%20method%20will%20resolve%20to%20false.) that this is a known limitation. It doesn't work with all Android app launchers.

**Comment by nathankota** [comment]
The notification badge works within the app on my Android device, as expected, just not on some Android app launchers, as described in Scott's previous comment. Closing this based on the documentation he provided:
![image](https://user-images.githubusercontent.com/15659642/192784643-13ecbde0-9cd3-4660-85f4-4d77c735bac7.png)
