### ISSUE TITLE
Add org dropdown

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#80]
Once we have a domain/list from DWR, add the ability for Contractor and Agency roles to select their organization when completing their profile (#71 )

**Comment by nathankota** [comment]
This is the old list, and will not suffice 

![image](https://user-images.githubusercontent.com/15659642/142030081-7559308d-eb21-46b6-8a89-b77649d171a2.png)

**Comment by nathankota** [comment]
[This](https://docs.google.com/spreadsheets/d/1aoDbmI37Z7hxpGE6CtQbI2e66JntDxemiexGeM9ZJLo/edit#gid=0) is the list to start with.

**Comment by nathankota** [comment]
Also need to incorporate the dropdown (or text if `Other`) on the user profile page (#73) if user needs to edit.

**Comment by stdavis** [comment]
Also check if the org text box should be showing up on the new user registration screen for public users.

**Comment by nathankota** [comment]
> Also check if the org text box should be showing up on the new user registration screen for public users.

It should not. I just logged in with my personal gmail account and, although I already went through the registration process with that account months ago, I do not think the org selection appears there. I know it doesn't on the public user profile page.

**Comment by nathankota** [comment]
This seems to work, and adds each new entry to the list. The selections I've added are highlighted below:

![image](https://user-images.githubusercontent.com/15659642/163888270-673b6e7f-4798-42e1-a0e1-e1597e7cbdbd.png)
