### ISSUE TITLE
New User Notification Emails

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#82]
Wire up email to be sent to admins when a new user registers that contain links for approval or denial.

Email should contain links to show the requested role, and to approve as any of the following roles, or to reject the user. 
- contractor
- agency
- admin

The email should be sent to the new google group from #75.

When a user is denied, their user account should be marked as such (approved=false) and any new attempts to submit data should be denied.

@nathankota Does this sound OK to you?

**Comment by stdavis** [comment]
@nathankota Should I just send the approval emails to all of the users that have a role of `admin` in the database? Otherwise, we'd need to keep a separate table or some other storage mechanism for keeping track of who gets what emails.

**Comment by nathankota** [comment]
> Email should contain links to approve a new user as the role that they chose in the app or as an admin. It should also contain a link to deny the user.
Can the approve link default to the role chosen in the app, but allow admin to apply _any_ role to the user, as well as deny?

**Comment by stdavis** [comment]
This is how it looks currently. Let me know if there are any changes that you would like:
![image](https://user-images.githubusercontent.com/1326248/128905265-b55c6903-43e1-4e18-8cb3-10b7794c0d78.png)

**Comment by nathankota** [comment]
The options and message look good. I assume the verbiage about rejection will change based on the decision to mark rejected users as `approved = false`.

**Comment by stdavis** [comment]
Here's a new version. Let me know if any other verbiage should be changed:
![image](https://user-images.githubusercontent.com/1326248/128940060-1aeb61d5-3c9f-4af5-8c60-651f1932106b.png)

**Comment by nathankota** [comment]
Looks great to me and I am checking with client to validate.

**Comment by stdavis** [comment]
OK. I just need the google group that they want these emails sent to. I also added some text to let you know if the email is coming from the staging environment.

**Comment by nathankota** [comment]
contacted WVC team

**Comment by stdavis** [comment]
Group is `wvc-dnr-dwr-notify@utah.gov`

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/130516958-f041a90f-bf64-4594-bc0c-1f3bb107a00a.png)

**Comment by stdavis** [comment]
I've completed Daniel's latest request of adding a better error message for users that have already been approved or rejected.

**Comment by steveoh** [comment]
Do you send an email to the group saying that the person was accepted as x or show that the user was already approved as x if they click on a different link after someone has approved or declined them?

**Comment by stdavis** [comment]
> Do you send an email to the group saying that the person was accepted as x or show that the user was already approved as x if they click on a different link after someone has approved or declined them?

The latter.

**Comment by steveoh** [comment]
Will they have a chance to change that information if someone clicked the wrong button?

**Comment by stdavis** [comment]
No, not currently without editing the database. Any suggestions for this use case? I wondered about just allowing links to override, but then I didn't feel like that was very secure. Old links would work forever.

**Comment by stdavis** [comment]
Maybe I just create an expiration date for links and then allow them to be used multiple times until they expire? That would satisfy the "I clicked the wrong link" issue as well as be more secure than allowing links to work forever. Maybe they would expire in a week or so to give the admins plenty of time to act on them.

**Comment by nathankota** [comment]
how about 2 weeks

**Comment by steveoh** [comment]
That sounds normal unless you are planning to build a place to manage users at a later point.

**Comment by nathankota** [comment]
> That sounds normal unless you are planning to build a place to manage users at a later point.

That is the preference, but also scope change and an enhancement that we will table until later.

**Comment by stdavis** [comment]
I wonder if I should also send an email to admins when a user has been approved or rejected? So that they know that it has been acted upon? Maybe that would get annoying to get a confirmation email after clicking on a link? I'm just thinking that there's no way for other admins to know that a user has been approved.

**Comment by nathankota** [comment]
Good point and question and, unfortunately, more justification for an admin page to view/manage roles.

**Comment by stdavis** [comment]
My understanding of the remaining actions items for this issue:
- [ ] allow for approval/rejection links to be used multiple times to allow for correction if the admin accidentally clicked the incorrect link
- [ ] add a two week expiration date on links after which they will no longer work
- [ ] add a secondary notification email letting admins know when a user has been approved or rejected

@nathankota Does this look correct to you?

**Comment by nathankota** [comment]
Yes, this looks correct. What happens after the two week expiration? Someone would have to access the database to approve a user?

**Comment by nathankota** [comment]
Let's stick with two weeks.

**Comment by stdavis** [comment]
I added this note to the registration notification email:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/1326248/162064311-f6e6a816-5128-4e73-b023-31bfd9b1e974.png">

This is what the error message looks like if you try to approve a user after two weeks:
![image](https://user-images.githubusercontent.com/1326248/162061508-50e36e2f-eb9c-40a3-afc9-95f3fe802272.png)

Approved email notification sent to admins:
![image](https://user-images.githubusercontent.com/1326248/162063938-6e37460d-78b6-4383-a6be-83eff532ddd2.png)

Reject email notification sent to admins:
![image](https://user-images.githubusercontent.com/1326248/162063961-4174e3e0-0846-4813-a0ae-b8d8670052e5.png)

Any improvements to the verbiage above are welcome and easy to update.

**Comment by nathankota** [comment]
I'm going to go ahead and validate and close this, and if new issues arise as the clients get around to testing it, we can open new ones.

**Comment by stdavis** [comment]
I just realized that we may have a missing piece to this issue; we don't send an email to the user letting them know that they have been approved or rejected.

@nathankota I don't remember seeing this in the specs but maybe it was assumed? Either way, would you like me to implement it? I don't think that it would take more than an hour or two.

**Comment by nathankota** [comment]
Wow, yes, that is important. Good catch, and please implement when you have a chance. I also don't recall if we tell the agency and contractor users that they require approval when they sign up, do you?

**Comment by stdavis** [comment]
> I also don't recall if we tell the agency and contractor users that they require approval when they sign up, do you?

We do not. That's another oversight. I've created new issues for both of these:

https://github.com/agrc/roadkill-mobile/issues/173

https://github.com/agrc/roadkill-mobile/issues/174
