### ISSUE TITLE
Trouble connecting to database in BigQuery

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#84]
Jessie:
> I'm having some trouble accessing the database in BigQuery. I'm following [this](https://cloud.google.com/bigquery/docs/cloud-sql-federated-queries) document, but I keep hitting connection errors. I've also tried using the connection ID in a federated query in the console, and it also fails to connect. 

![enableAPI](https://user-images.githubusercontent.com/15659642/129104098-f528f3cc-f369-4701-abbb-d12d4390fa76.JPG)

**Comment by stdavis** [comment]
I've added the `bigqueryconnection.googleapis.com` to the dev project. Please ask Jessie to try it again.

**Comment by nathankota** [comment]
once this is resolved #86 can be tested
