### ISSUE TITLE
Federated queries

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#86]
Creating the queries is mostly on the client, but this is relying on #84 to be resolved first.

> Jonathon Foster says that our only option for allowing access to the cloud SQL database is for clients to run [auth proxy](https://cloud.google.com/sql/docs/postgres/sql-proxy).
> 
> Keaton suggested using [federated queries](https://cloud.google.com/bigquery/docs/cloud-sql-federated-queries) to give them access to the database in big query. Not sure which the client prefers. We'll have to ask them. @nathankota Do you want to start this conversation? It might be best to see how they are interacting with the data in the new collars system. Then maybe we can work up something that they are already familiar with.

They prefer the Keaton-recommended federated queries option. Is that going to be okay?

_Originally posted by @nathankota in https://github.com/agrc/roadkill-mobile/issues/26#issuecomment-888483782_

**Comment by nathankota** [comment]
Scott's response:

> Yes! I believe that the federated queries option is the easiest option. There is a database up and running in ut-dts-agrc-roadkill-dev that they are welcome to point their federated queries at. Let me know if they need anything else from me to access it.

**Comment by nathankota** [comment]
after #84 is resolved, this can be tested

**Comment by stdavis** [comment]
Jessie has confirmed that this is working now.
