### ISSUE TITLE
Add About page

### ISSUE THREAD

**Issue by nathankota** [agrc/roadkill-mobile#92]
Add an About page to the main menu of the app to contain disclaimers and other information, as well as the version and build numbers #91.

**Comment by stdavis** [comment]
Another thing that could go on this page is a change log if we want to present that to users.

**Comment by stdavis** [comment]
I ended up adding this screen today since I needed a place to put a clear base map cache button. It currently looks like this:
![image](https://user-images.githubusercontent.com/1326248/190713137-45293429-379b-4a30-b0a5-eb9e5d82b706.png)

Send me the text of a disclaimer and I can easily add it.

**Comment by stdavis** [comment]
I added this text from Blair's latest email:

>The Utah Wildlife-Vehicle Collision Reporter all (WVCR) is a smartphone-based system for reporting animals that have been involved in vehicle collisions. Data collected from this app will allow UDWR and UDOT to reduce wildlife-vehicle collisions make highways safer for drivers and wildlife.

It can easily be changed. Just let me know.

**Comment by nathankota** [comment]
Two very slight changes below in bold, italicized...
 
 > The Utah Wildlife-Vehicle Collision Reporter **_app_** (WVCR) is a smartphone-based system for reporting animals that have been involved in vehicle collisions. Data collected from this app will allow UDWR and UDOT to reduce wildlife-vehicle collisions _**and**_ make highways safer for drivers and wildlife.
>

**Comment by nathankota** [comment]
validated and closing...if client has other ideas we will track in another issue
